Repository wecode-bootcamp-korea/33-backend-westagram-3, pull requests merged in 2022-05, with the labels that each got.

#2 [33기 이예은] Mission 2: 모델링
  students/mia/users/__init__.py
  students/mia/users/admin.py
  students/mia/users/apps.py
  students/mia/users/migrations/0001_initial.py
  students/mia/users/migrations/0002_alter_user_email_alter_user_updated_at.py
  students/mia/users/migrations/__init__.py
  students/mia/users/models.py
  students/mia/users/tests.py
  students/mia/users/views.py
  students/mia/westagram/settings.py
Labels: 멘토 리뷰 요청

#3 [33기 박준형] Mission 1: Django 초기 세팅 #33
  students/junhyung/.gitignore
  students/junhyung/manage.py
  students/junhyung/requirements.txt
  students/junhyung/westagram/__init__.py
  students/junhyung/westagram/asgi.py
  students/junhyung/westagram/settings.py
  students/junhyung/westagram/urls.py
  students/junhyung/westagram/wsgi.py
Labels: 완료

#5 [33기 박준형] Mission 2: 모델링
  students/junhyung/users/__init__.py
  students/junhyung/users/admin.py
  students/junhyung/users/apps.py
  students/junhyung/users/migrations/0001_initial.py
  students/junhyung/users/migrations/0002_rename_user_mail_user_mail_and_more.py
  students/junhyung/users/migrations/0003_alter_user_mail_alter_user_password.py
  students/junhyung/users/migrations/0004_alter_user_mail.py
  students/junhyung/users/migrations/__init__.py
  students/junhyung/users/models.py
  students/junhyung/users/tests.py
  students/junhyung/users/views.py
  students/junhyung/westagram/settings.py
Labels: 멘토 리뷰 요청

#4 [33기 이예은] Mission 3: 회원가입 기능 구현
  students/mia/users/apps.py
  students/mia/users/urls.py
  students/mia/users/views.py
  students/mia/westagram/urls.py
Labels: 멘토 리뷰 요청

#6 [33기 이예은] Mission 4: 로그인 기능 구현
  students/mia/users/urls.py
  students/mia/users/views.py
Labels: 멘토 리뷰 요청

#7 [33기 이예은] Mission 5: 회원가입 비밀번호 암호화 적용
  students/mia/users/views.py
Labels: 멘토 리뷰 요청

#8 [33기 박준형] Mission 3. 회원가입 기능 구현
  students/junhyung/users/models.py
  students/junhyung/users/urls.py
  students/junhyung/users/views.py
  students/junhyung/westagram/settings.py
  students/junhyung/westagram/urls.py
Labels: 멘토 리뷰 요청

#11 Add: westarbucks
  students/bada/crud1/bada/__init__.py
  students/bada/crud1/bada/admin.py
  students/bada/crud1/bada/apps.py
  students/bada/crud1/bada/migrations/0001_initial.py
  students/bada/crud1/bada/migrations/0002_allergy_created_at_allergy_drink_created_at_and_more.py
  students/bada/crud1/bada/migrations/__init__.py
  students/bada/crud1/bada/models.py
  students/bada/crud1/bada/tests.py
  students/bada/crud1/bada/views.py
  students/bada/crud1/crud1/__init__.py
  students/bada/crud1/crud1/asgi.py
  students/bada/crud1/crud1/settings.py
  students/bada/crud1/crud1/urls.py
  students/bada/crud1/crud1/wsgi.py
  students/bada/crud1/health_check/__init__.py
  students/bada/crud1/health_check/admin.py
  students/bada/crud1/health_check/apps.py
  students/bada/crud1/health_check/migrations/__init__.py
  students/bada/crud1/health_check/models.py
  students/bada/crud1/health_check/tests.py
  students/bada/crud1/health_check/views.py
  students/bada/crud1/manage.py
Labels: 완료

#10 [33기 이예은] Mission 6: 로그인 JWT 발급
  students/mia/users/migrations/0003_remove_user_mobile_number_remove_user_name.py
  students/mia/users/migrations/0004_user_mobile_number_user_name.py
  students/mia/users/models.py
  students/mia/users/views.py
  students/mia/westagram/settings.py
Labels: 멘토 리뷰 요청

#9 [33기 박준형] Mission 4: 로그인 기능 구현
  students/junhyung/users/migrations/0005_alter_user_password.py
  students/junhyung/users/urls.py
  students/junhyung/users/views.py
Labels: 리뷰 진행 중

#12 Bada/assignment1
  students/bada/crud1/bada/urls.py
  students/bada/crud1/bada/views.py
  students/bada/crud1/crud1/urls.py
Labels: 완료

#13 [33기 박준형] Mission 5. 암호화
  students/junhyung/requirements.txt
  students/junhyung/users/views.py
Labels: 완료
